import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow"
});

export const metadata: Metadata = {
  title: "eZoom Fit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={barlow.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
